version: '3.8'

services:
  motive-stack:
    build: .
    container_name: motive_stack_1
    network_mode: host
    environment:
      - ConnectionStrings__DefaultConnection=Server=motive-db;Port=3306;Database=ecen424_db_project;User ID=root;Password=motivepassword;SslMode=None;AllowPublicKeyRetrieval=True;
    depends_on:
      - motive-db

  motive-db:
    image: mysql:8.0
    container_name: motive-db
    network_mode: host 
    environment:
      - MYSQL_ROOT_PASSWORD=motivepassword
      - MYSQL_DATABASE=ecen424_db_project
    volumes:
      - ./database/motiveDB.sql:/docker-entrypoint-initdb.d/init.sql
